# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/30e3ab42-9ebe-4c39-b85a-6219ad600415";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a982f534-9610-4613-b48e-b0cff5f77423".device = "/dev/disk/by-uuid/a982f534-9610-4613-b48e-b0cff5f77423";
  boot.initrd.luks.devices."luks-ab2186be-8d10-413a-88f2-d82df2b0f68f".device = "/dev/disk/by-uuid/ab2186be-8d10-413a-88f2-d82df2b0f68f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/89AD-F74B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/366867a4-0437-42b2-ad10-58aa62aa23c9"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
