# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a9d01ae9-dcb1-4459-9aab-525ac6ae8f3c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c0bbe1e8-d7d0-4e0d-8ae0-fc8fe98c1561".device = "/dev/disk/by-uuid/c0bbe1e8-d7d0-4e0d-8ae0-fc8fe98c1561";
  boot.initrd.luks.devices."luks-e66cafe4-6896-4f42-ac2b-4bf063ae99d9".device = "/dev/disk/by-uuid/e66cafe4-6896-4f42-ac2b-4bf063ae99d9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9A7B-270F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4285082b-a1ff-4d1b-b8c2-5101e9555b87"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
