# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/407afb39-6250-4b23-8a07-d6f2cb4cdc84";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d2378be4-d3d5-4086-be77-d54909b962a0".device = "/dev/disk/by-uuid/d2378be4-d3d5-4086-be77-d54909b962a0";
  boot.initrd.luks.devices."luks-549b7b8e-8bb4-4f75-8f23-2c224a2019cc".device = "/dev/disk/by-uuid/549b7b8e-8bb4-4f75-8f23-2c224a2019cc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CE0A-1758";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8e09475a-8d2f-43ec-8abf-4014e0b9a435"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f3u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
